### ISSUE TITLE
Supported attributes for SCardGetAttrib?

### ISSUE THREAD

**Issue by ctadlock** [acshk/acsccid#11]
What, if any attributes are supported for `SCardGetAttrib`?

* https://msdn.microsoft.com/en-us/library/windows/desktop/aa379559(v=vs.85).aspx
* https://pcsclite.alioth.debian.org/api/group__API.html#gaacfec51917255b7a25b94c5104961602

**Comment by godfreychung** [comment]
You can find it from `IFDHGetCapabilities()` from ifdhandler.c.
