### ISSUE TITLE
acr39u-u1

### ISSUE THREAD

**Issue by digitalcomposer** [acshk/acsccid#12]
Hi

We use 072F B10C ACR39U-U1 on RASPBIAN STRETCH, but the device is recognized as 072F B100 ACR39U.

We have the problem when the card is removed one time we can not used again, we must to disconnect the reader to use the card again.

Thank you for your help.

And sorry for my english.

**Comment by godfreychung** [comment]
Please provide the log using the following command:
`sudo LIBCCID_ifdLogLevel=0x0007 pcscd -fd | tee log.txt`

**Comment by digitalcomposer** [comment]
pi@raspberrypi:~ $ sudo LIBCCID_ifdLogLevel=0x0007 pcscd -fd | tee log.txt
00000000 debuglog.c:289:DebugLogSetLevel() debug level=debug
00000826 configfile.l:282:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00000082 configfile.l:319:DBGetReaderListDir() Skipping non regular file: .
00000018 configfile.l:319:DBGetReaderListDir() Skipping non regular file: ..
00000016 configfile.l:358:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00000232 pcscdaemon.c:655:main() pcsc-lite 1.8.20 daemon ready.
00020204 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000866 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000656 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9514, path: /dev/bus/usb/001/002
00000481 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0xEC00, path: /dev/bus/usb/001/003
00000444 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9514, path: /dev/bus/usb/001/002
00000429 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x17EF, PID: 0x608D, path: /dev/bus/usb/001/004
00000445 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9514, path: /dev/bus/usb/001/002
00000434 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x413C, PID: 0x2003, path: /dev/bus/usb/001/005
00000448 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9514, path: /dev/bus/usb/001/002
00000428 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/006
00000018 hotplug_libudev.c:433:HPAddDevice() Adding USB device: ACS ACR39U ICC Reader
00000126 readerfactory.c:1079:RFInitializeReader() Attempting startup of ACS ACR39U ICC Reader 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00000701 readerfactory.c:954:RFBindFunctions() Loading IFD Handler 3.0
00000087 ifdhandler.c:1961:init_driver() Driver version: 1.4.26
00002990 ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000021 ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00000507 ifdhandler.c:2002:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x0007
00000010 ifdhandler.c:111:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/b100:libudev:0:/dev/bus/usb/001/006
00000012 ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:072f/b100:libudev:0:/dev/bus/usb/001/006
00000026 ccid_usb.c:269:OpenUSBByName() interface_number: 0
00000007 ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/6
00000009 ccid_usb.c:287:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00003012 ccid_usb.c:305:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000024 ccid_usb.c:306:OpenUSBByName() ifdProductString: Generic CCID driver
00000010 ccid_usb.c:307:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00012565 ccid_usb.c:391:OpenUSBByName() Try device: 1/6
00000038 ccid_usb.c:401:OpenUSBByName() vid/pid : 072F/B100
00000007 ccid_usb.c:448:OpenUSBByName() Checking device: 1/6
00000010 ccid_usb.c:519:OpenUSBByName() Trying to open USB bus/device: 1/6
00000886 ccid_usb.c:621:OpenUSBByName() Found Vendor/Product: 072F/B100 (ACS ACR39U ICC Reader)
00000030 ccid_usb.c:623:OpenUSBByName() Using USB bus/device: 1/6
00000013 ccid_usb.c:680:OpenUSBByName() bNumDataRatesSupported is 0
00103080 -> 000000 65 00 00 00 00 00 00 00 00 00 
00001584 <- 000000 81 00 00 00 00 00 00 02 00 01 
00000018 -> 000000 65 00 00 00 00 00 01 00 00 00 
00001479 <- 000000 81 00 00 00 00 00 01 02 00 01 
00000017 ifdhandler.c:382:IFDHGetCapabilities() tag: 0xFB3, usb:072f/b100:libudev:0:/dev/bus/usb/001/006 (lun: 0)
00000011 readerfactory.c:395:RFAddReader() Using the reader polling thread
00001586 ifdhandler.c:382:IFDHGetCapabilities() tag: 0xFAE, usb:072f/b100:libudev:0:/dev/bus/usb/001/006 (lun: 0)
00000011 ifdhandler.c:473:IFDHGetCapabilities() Reader supports 1 slot(s)
00000814 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9514, path: /dev/bus/usb/001/002
00000132 readerfactory.c:1420:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00

**Comment by digitalcomposer** [comment]
I use this to connect xfreerdp -sec-nla /f /d:YourDomain /smartcard:072F:B100 /v:IP address

**Comment by godfreychung** [comment]
According to the log, you are using retail version of ACR39U with `ccid` (**NOT** `acsccid`). Please note that ACR39U (PID: B10C) is a customized version for specific customer.

Please reproduce your problem and provide the log from `pcscd`. It may be the problem in `xfreerdp`.
