### ISSUE TITLE
ACR123U not detected in Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by takeruadelbert** [acshk/acsccid#27]
Hi ACS team, I would like to seek some advices and solutions regarding my problem.
I have device ACR123U and using Ubuntu 20.04 LTS OS.
However, the PCSC driver seems not working properly.
I did download the driver from here `https://www.acs.com.hk/en/products/343/acr123u-intelligent-contactless-reader/`
and I couldn't find a driver for Ubuntu Focal Fossa (I found only up to 19.10 (Eoan).
I tried to install Eoan driver in my Focal Fossa and when I check PCSC service status it shows like this :

![image](https://user-images.githubusercontent.com/17585173/105794918-8c778480-5fbe-11eb-87a6-2f27dd336af4.png)

However when I type `lsusb` the OS seems to show the device correctly though
![image](https://user-images.githubusercontent.com/17585173/105794997-b03aca80-5fbe-11eb-8868-6beedd10388d.png)

Is there any solutions for this?

**Comment by godfreychung** [comment]
Can you try to install libacsccid1 package from Ubuntu?
i.e. `sudo apt-get install libacsccid1`

**Comment by takeruadelbert** [comment]
@godfreychung I have already installed that lib anyway
here's the output :
![image](https://user-images.githubusercontent.com/17585173/105798713-5f7aa000-5fc5-11eb-9d74-e67b8e43e5bd.png)

Is there any other libs that I should install?

**Comment by godfreychung** [comment]
It seems to be a firmware issue.
Please kindly contact ACS for technical support.
