### ISSUE TITLE
ACR122U Reader unable to Authenticate and read from memory block

### ISSUE THREAD

**Issue by arpit-mehra** [acshk/acsccid#30]
I have been facing a problem with a ACR122U NFC Reader where it always returns `63 00` when I try to authenticate with the keys and access a memory block. I am trying to list down the versions and OS I am using for reference. 
**Versions**
smart card reader driver name and version - ACR 122U PICC Interface
pcsc-lite-libs-1.9.0-2.fc33.x86_64
pcsc-lite-1.9.0-2.fc33.x86_64
pcsc-lite-ccid-1.4.29-3.el8.x86_64
pcsc-lite-acsccid-1.1.8-1.el8.x86_64
the output of the command /usr/sbin/pcscd --version
pcsc-lite version 1.9.0.
**Platform**
Operating system or GNU/Linux distribution name and version - RHEL 8

Also attaching the output of 
`sudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color | tee log.txt`

[log.txt](https://github.com/acshk/acsccid/files/7056066/log.txt)

Is there a setting on the driver, that needs any change ? I have another ACR1252 which works perfectly fine with the same set of keys, reading the same memory block, exactly the same code. 
I would really appreciate any pointers on this one.

**Comment by godfreychung** [comment]
Your log did not show any APDU to the reader. I think that you may need to save the log again for ACR122U and ACR1252U.

**Comment by arpit-mehra** [comment]
Attaching the  logs again. 

[log-ACR122U.txt](https://github.com/acshk/acsccid/files/7084766/log-ACR122U.txt)
[log-ACR1252.txt](https://github.com/acshk/acsccid/files/7084768/log-ACR1252.txt)

**Comment by godfreychung** [comment]
Your log did not show any APDU to the reader. Please make sure that you have run the program. You will see the command starting with `6F` and the response starting with `80`.

**Comment by arpit-mehra** [comment]
Hi, Apologies, I had to restart my service to be able to detect the daemon started again in the foreground. Attaching the ACR122U logs here for your reference. 
[log-Acr122U-APDU.txt](https://github.com/acshk/acsccid/files/7101233/log-Acr122U-APDU.txt)

I have replaced the decryption keys with XX

**Comment by arpit-mehra** [comment]
[log-Acr122U-APDU.txt](https://github.com/acshk/acsccid/files/7101229/log-Acr122U-APDU.txt)

**Comment by arpit-mehra** [comment]
Just wanted to check if something in the logs reveals if we are doing something wrong. Or is it the hardware or commands that we are sending.

**Comment by godfreychung** [comment]
I can't find any issue in your command.
It may be card problem or you are using a wrong key.
Please use a blank card with a default key to see if the issue can be reproduced.

**Comment by arpit-mehra** [comment]
Thanks for your response @godfreychung 
We have tried using the same card, with the same key, on another reader that works perfectly fine. Also, the same card, works on my phone's NFC Reader with the keys that I specify, which makes me think its either on the reader itself, or the driver is not happy talking to this NFC Reader.

**Comment by godfreychung** [comment]
I think that you may need to try more different cards to see if the reader is damaged or not.
You can also contact ACS for technical support.
