### ISSUE TITLE
SourceForge website not updated

### ISSUE THREAD

**Issue by Jakuje** [acshk/acsccid#34]
Hi, the last versions were published on sourceforge in tar.bz format and the current is now only on github. Is the sourceforge website going to be updated or the new releases will be published only here on github?

https://acsccid.sourceforge.io/

**Comment by godfreychung** [comment]
Yes, the web site will be updated. Currently, you can get the latest version (acsccid-1.1.9.tar.bz2) from SourceForge.

**Comment by godfreychung** [comment]
Done.
