### ISSUE TITLE
ACR1252U-M1 Support?

### ISSUE THREAD

**Issue by josx** [acshk/acsccid#8]
I have bought a ACR1252U-M1, and it is not on the supported list.
By now there is support for:

```
072F 223B ACR1252U-A1         ACS ACR1252 1S CL Reader
072F 223E ACR1252U-A2         ACS ACR1252 CL Reader
072F 223D ACR1252U BL         ACS ACR1252 USB FW_Upgrade v100
072F 2244 ACR1252U-A1 (PICC)  ACS ACR1252U BADANAMU MAGIC READER
```

But ACR1252u-M1 has the same ids that ACR1252U-A1.
```ID 072f:223b Advanced Card Systems, Ltd```

**Comment by godfreychung** [comment]
Fixed in 4dd8f62.
